#!/bin/sh
# Print a version string containing the Subversion repo version info.

scriptversion=2011-08-27.01; # UTC

#
# Copyright 2011 Gary R. Van Sickle (grvs@users.sourceforge.net).
#
# This file is part of CoFlo.
#
# CoFlo is free software: you can redistribute it and/or modify it under the
# terms of version 3 of the GNU General Public License as published by the Free
# Software Foundation.
#
# CoFlo is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.  See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along with
# CoFlo.  If not, see <http://www.gnu.org/licenses/>.

# Functionality based on Autoconf's own git-version-gen script.

tarball_version_file=$1;

# The svnversion executable.
SVNVERSION=`which svnversion`;
if test $? -ne 0;
then
	# Couldn't find an svnversion on PATH.
	# This is only a problem if we don't have a valid .tarball-version.
	# Stub in "svnversion" here, but it will probably fail below.
	SVNVERSION=svnversion;
fi

# Does the specified tarball version file exist?
if test -f $tarball_version_file;
then
	echo "$0: INFO: Getting rev info from $tarball_version_file" 1>&2;
	version_string=`cat $tarball_version_file` || exit 1;
fi

# Did we get a version string?
if test -z "$version_string";
then
	# No, try svnversion.
	# Can we execute $SVNVERSION?
	if test -x $SVNVERSION;
	then
		# We should be able to execute $SVNVERSION.
		version_string=`$SVNVERSION -n` \
			|| { version_string=UNKNOWN; echo "$0: WARNING: svnversion -n failed" 1>&2; };
		version_string=`echo $version_string | tr ':' '.'`;
		if test "x$version_string" = "xexported";
		then
			version_string=UNKNOWN
		fi
	else
		# We aren't able to execute $SVNVERSION, or it doesn't exist.
		echo "$0: WARNING: Can't execute $SVNVERSION" 1>&2;
	fi
fi

if test -z "$version_string"
then
	# Can't get a version string.
	version_string=UNKNOWN
fi

echo "$0: INFO: Determined version info: $version_string" 1>&2;

echo "$version_string"
